import { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, LoaderCircle, MessageSquareText, Pencil, RefreshCw } from 'lucide-react';
import { Link } from 'react-router-dom';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { configureNoteInbox, getNoteInboxStatus, syncNoteInbox } from '@/api';
import type { NoteInboxStatus, NoteStyle } from '@shared/api.interface';

export default function NoteInboxPage() {
  const [chatId, setChatId] = useState(''); const [status, setStatus] = useState<NoteInboxStatus | null>(null); const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const noteStyle: NoteStyle = 'learning';
  async function refresh(): Promise<void> { try { const next = await getNoteInboxStatus(); setStatus(next); setChatId(next.chatId || ''); } catch { toast.error('无法读取飞书收集箱状态'); } }
  useEffect(() => { void refresh(); }, []);
  async function save(): Promise<void> { if (!chatId.trim()) { toast.error('请填写飞书会话 ID'); return; } setSaving(true); try { const next = await configureNoteInbox({ chatId: chatId.trim(), noteStyle }); setStatus(next); setEditing(false); toast.success('收集箱配置已保存并启用'); } catch { toast.error('保存失败，请检查会话 ID 与飞书授权'); } finally { setSaving(false); } }
  async function sync(): Promise<void> { setSaving(true); try { const next = await syncNoteInbox(); setStatus(next); if (next.lastError) toast.error(next.lastError); else toast.success('已检查最新飞书消息'); } catch { toast.error('同步失败，请稍后重试'); } finally { setSaving(false); } }
  const configured = Boolean(status?.configured);
  return <main className="min-h-screen bg-[#f7f7f5] px-5 py-7 text-[#161616] md:px-10 md:py-10"><div className="mx-auto max-w-2xl"><header className="flex items-center justify-between border-b border-black/8 pb-5"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-[#3370ff] text-white"><MessageSquareText className="size-5" /></div><div><p className="text-sm font-semibold">飞书链接收集箱</p><p className="text-xs text-black/45">配置采集规则</p></div></div><Button asChild size="sm" variant="outline"><Link to="/"><ArrowLeft className="size-4" />返回入口</Link></Button></header><section className="mt-10 space-y-7"><div><h1 className="text-3xl font-semibold">{configured ? '收集箱已启用' : '绑定专用飞书会话'}</h1><p className="mt-3 text-sm leading-6 text-black/52">手机分享链接后，本机每 30 秒检查一次。消息记录请在独立的消息页面查看。</p></div>{configured && <div className="flex items-start gap-3 border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-emerald-600" /><div><p className="font-semibold">配置已持久化保存</p><p className="mt-1">有效链接消息 {status?.summary?.totalMessages ?? 0} 条。{status?.lastError || '监听运行中。'}</p></div></div>}<div className="border-y border-black/8 py-6"><label className="block text-sm font-medium">飞书会话 ID<Input className="mt-2 h-12 bg-white" disabled={configured && !editing} onChange={(event) => setChatId(event.target.value)} placeholder="oc_xxxxxxxxxxxxx" value={chatId} /></label></div><div className="flex flex-col gap-3 sm:flex-row">{!configured || editing ? <Button className="h-11 flex-1" disabled={saving} onClick={() => void save()}>{saving ? <LoaderCircle className="size-4 animate-spin" /> : <CheckCircle2 className="size-4" />}保存并启用</Button> : <Button className="h-11 flex-1" onClick={() => setEditing(true)} variant="secondary"><Pencil className="size-4" />修改配置</Button>}<Button asChild className="h-11" disabled={!configured} variant="outline"><Link to="/note-inbox/messages"><MessageSquareText className="size-4" />消息列表</Link></Button><Button className="h-11" disabled={saving || !configured} onClick={() => void sync()} variant="outline"><RefreshCw className="size-4" />立即检查</Button></div>{editing && configured && <Button className="text-black/55" onClick={() => { setEditing(false); setChatId(status?.chatId || ''); }} variant="ghost">取消修改</Button>}</section></div></main>;
}
